CREATE TABLE CONTA(
    ID_CLNT BIGINT AUTO_INCREMENT PRIMARY KEY,
    SLD_CNTA DECIMAL(19, 2) NOT NULL
);

CREATE TABLE LANCAMENTO (
    ID_LCMT BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIP_TRSC VARCHAR(8) NOT NULL,
    VLR_TRSC DECIMAL(19, 2) NOT NULL,
    ID_CLNT BIGINT NOT NULL,
    DTA_TRSC TIMESTAMP NOT NULL,
    CONSTRAINT FK_LANCAMENTO_CONTA_CLIENTE FOREIGN KEY (ID_CLNT) REFERENCES CONTA(ID_CLNT)
);

-- Cria um cliente default
INSERT INTO CONTA (SLD_CNTA) VALUES (2000.00);
